#!/bin/sh
#
# Copyright (c) 2010-2012 Jason J. Hellenthal <jhell@dataix.net>,
# All rights reserved.
#
# $Id$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE ABOVE COPYRIGHT AND LICENSE COVERS THE CONTENTS OF THE DIRECTORY TREE
# THAT FOLLOWS UNLESS EXPLICITLY INCLUDED IN THE CONTENTS OF A FILE OR
# DIRECTORY THAT IS CONTAINED WITHIN THE FOLLOWING TREE.
#

echo "# $(hostname)"
echo "# $(uname -a |xargs)"
echo
echo "# Email your Administrator the output from this script"
echo "# as a attachment and ask them to add what they feel are"
echo "# the proper policies for you on this machine given the"
echo "# values that have been generated by use of this script."
echo "#"
echo "# The default location for this file in FreeBSD is:"
echo "# /usr/local/etc/PolicyKit/PolicyKit.conf"
echo "#"

test -n "$1" || echo "usage: $(basename $0) username"
test -n "$1" || exit 1

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <!-- -*- XML -*- -->"
echo
echo "<!DOCTYPE pkconfig PUBLIC \"-//freedesktop//DTD PolicyKit Configuration 1.0//EN\""
echo "\"http://hal.freedesktop.org/releases/PolicyKit/1.0/config.dtd\">"
echo
echo "<!-- See the manual page PolicyKit.conf(5) for file format -->"
echo
echo "<config version=\"0.1\">"
echo "    <match user=\"root\">"
echo "        <return result=\"yes\"/>"
echo "    </match>"

for auth_config in $(polkit-action); do
    echo "    <match action=\"${auth_config}\">"
    echo "        <match user=\"$1\">"
    echo "            <return result=\"yes\"/>"
    echo "        </match>"
    echo "    </match>"
done

echo "    <define_admin_auth group=\"wheel\"/>"
echo "</config>"
