#!/bin/sh
# Start gpg-agent if it is not running as the current user.

umask 077

pgrep -U $LOGNAME gpg-agent >>/dev/null 2>&1 ||/usr/local/bin/gpg-agent --daemon --write-env-file "${HOME}/.gpg-agent-info" >>/dev/null 2>&1
